flaskblog/models.py
from datetime import datetime
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from flask import current_app
from flaskblog import db, login_manager
from flask_login import UserMixin


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    image_file = db.Column(db.String(20), nullable=False, default='default.jpg')
    password = db.Column(db.String(60), nullable=False)
    posts = db.relationship('Post', backref='author', lazy=True)

    def get_reset_token(self, expires_sec=1800):
        s = Serializer(current_app.config['SECRET_KEY'], expires_sec)
        return s.dumps({'user_id': self.id}).decode('utf-8')

    @staticmethod
    def verify_reset_token(token):
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            user_id = s.loads(token)['user_id']
        except:
            return None
        return User.query.get(user_id)

    def __repr__(self):
        return f"User('{self.username}', '{self.email}', '{self.image_file}')"


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    date_posted = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    content = db.Column(db.Text, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)

    def __repr__(self):
        return f"Post('{self.title}', '{self.date_posted}')"


class File(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    date_posted = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    link = db.Column(db.Text, nullable=False)
    image_preview = db.Column(db.String(20), nullable=False, default='default.jpg')
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)

    def __repr__(self):
        return f"File('{self.title}', '{self.date_posted}')"

flaskblog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

flaskblog/main/routes.py
from flask import render_template, request, Blueprint
from flaskblog.models import Post
from .data import *

main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home")
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('home.html', posts=posts)


@main.route("/about")
def about():
    return render_template('about.html', title='About')


@main.route("/entourage")
def entourage():
    return render_template('entourage.html', title='Entourage', articles=articles)


@main.route("/new_article")
def new_article():
    return render_template('new_article.html', title='New Article')


@main.route("/tutorials")
def tutorials():
    return render_template('tutorials.html', title='Tutorials', videos=videos)


@main.route("/tutorial001")
def tutorial001():
    return render_template('001.html', title='Tutorial001')


@main.route("/new_tutorials")
def new_tutorials():
    return render_template('new_tutorials.html', title='New Tutorials')


@main.route("/dwg")
def dwg():
    return render_template('dwg.html', title='Dwg')


@main.route("/new_dwg")
def new_dwg():
    return render_template('new_dwg.html', title='New File')


@main.route("/scripts")
def scripts():
    return render_template('scripts.html', title='Scripts')


@main.route("/models")
def models():
    return render_template('models.html', title='Models')


@main.route("/search")
def search():
    return render_template('search.html', title='Search')


@main.route("/search1")
def search1():
    return render_template('search1.html', title='Search1')


@main.route("/search2")
def search2():
    return render_template('search2.html', title='Search2')


@main.route("/icons")
def icons():
    return render_template('icons.html', title='Projects')


@main.route("/new_project")
def new_project():
    return render_template('new_project.html', title='New Project')


@main.route("/maps")
def maps():
    return render_template('maps.html', title='Maps')


@main.route("/map1")
def map1():
    return render_template('map.html', title='Brzezin')


@main.route("/map2")
def map2():
    return render_template('map2.html', title='lodz botanic garden')


@main.route("/map3")
def map3():
    return render_template('map3.html', title='lodz Piotrkowska Street')


@main.route("/sketchmap")
def sketchmap():
    return render_template('sketchmap.html', title='Map Sketch')


@main.route("/sketch3d")
def sketch3d():
    return render_template('sketch3d.html', title='3D Map Sketch')


@main.route("/map01")
def map01():
    return render_template('arcgis/map01.html', title='Map 3D')


@main.route("/map4")
def map4():
    return render_template('map4.html', title='Piotrkowska Street')


@main.route("/map5")
def map5():
    return render_template('map5.html', title='Lodz Map of Murals')

@main.route("/projectshow/<int:proj_id1>")
def projectshow(proj_id1):
    project = next((x for x in gh_scripts if x["proj_id"] == proj_id1), None)
    return render_template('projectshow.html', title='projectshow', project=project)

flaskblog/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from flaskblog import db
from flaskblog.models import Post
from flaskblog.posts.forms import PostForm

posts = Blueprint('posts', __name__)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='New Post',
                           form=form, legend='New Post')


@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post',
                           form=form, legend='Update Post')


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))

flaskblog/templates/001.html
{% extends "layout.html" %}
{% block content %}
  <main id="post-283102" class="instapaper_body h-entry e-content">

    <header class="mega-header header-breadcrumbs single-video-header header-with-bottom-gradient" id="maincontent">

      <style>
        .mega-header::before {
          content: "";
          position: absolute;
          top: 0;
          left: 0;
          width: 100%;
          height: 100%;
          background-image:
            radial-gradient(ellipse closest-side, rgba(15, 14, 22, 0.5), #100e17),
            url(https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/40786564395233.5ad0a38665840.jpg);
          background-size: cover;
          background-repeat: no-repeat;
          opacity: 0.75;
        }
      </style>

      <div class="mega-header-inside">

        <div class="mega-header-header">
          <span><span><span><a href="http://ccresources.herokuapp.com/" >Home</a> <span class="breadcrumb-separator">/</span> <span><a href="http://ccresources.herokuapp.com/" >Video Screencasts</a> <span class="breadcrumb-separator">/</span> <span class="breadcrumb_last">#001: Changing drawing backgrounds in photoshop</span></span></span></span></span>
          <h1 class="screen-reader">
            #170: Watch an Amateur Spin Up a React + Babel + Webpack + CSS Modules Project        </h1>

          <div class="article-content-meta">

       <div class="author-avatar">
      <a href="https://ymcmbennie.github.io/portfolio/">
        <img alt='Photo of Benson Sanga' src='https://scontent.flhr5-1.fna.fbcdn.net/v/t1.0-9/25659525_1660669194003997_812779653662270213_n.jpg?_nc_cat=102&_nc_ht=scontent.flhr5-1.fna&oh=4de2328aab11e7ea40fb38265d2803a3&oe=5D0BB7BE' srcset='' class='avatar avatar-80 photo' height='80' width='80' />    </a>
      <svg class="half-circle" width="80px" height="80px">
        <use xlink:href="#half-circle"></use>
      </svg>
    </div>

    <div class="author-name-area">
      <div class="author-name-prefix">
        Author
      </div>
      <a class="author-name" href="https://ymcmbennie.github.io/portfolio/">
        Benson Sanga</a>
    </div>

    <div class="article-comments-meta">
      <div class="comments-prefix">
        Comments    </div>
      <a class="comments-link" href="https://www.youtube.com/watch?v=pxNrUg7t0Mg">
                Go to Comments
              <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" class="icon-arrow-right">
  <path d="M7 12.5L23 12.5" stroke="url(#paint0_linear)" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
  <path d="M1 12.5H2" stroke="url(#paint1_linear)" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
  <path d="M17.5 7L23 12.5L17.5 18" stroke="url(#paint2_linear)" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
  <defs>
  <linearGradient id="paint0_linear" x1="10.7498" y1="12.5" x2="11.3447" y2="9.73465" gradientUnits="userSpaceOnUse">
  <stop stop-color="#FF8A00"/>
  <stop offset="1" stop-color="#DA1B60"/>
  </linearGradient>
  <linearGradient id="paint1_linear" x1="1.23436" y1="12.5" x2="2.00945" y2="12.2748" gradientUnits="userSpaceOnUse">
  <stop stop-color="#FF8A00"/>
  <stop offset="1" stop-color="#DA1B60"/>
  </linearGradient>
  <linearGradient id="paint2_linear" x1="18.789" y1="17.9995" x2="23.3162" y2="17.3419" gradientUnits="userSpaceOnUse">
  <stop stop-color="#FF8A00"/>
  <stop offset="1" stop-color="#DA1B60"/>
  </linearGradient>
  </defs>
  </svg>
      </a>
    </div>

        <div class="created">
        <div class="created-prefix">
          Published
        </div>
        <time datetime="">
          Mar 4, 2019      </time>
      </div>

          <div class="updated">
        <div class="updated-prefix">
          Updated
        </div>
        <time datetime="">
          Mar 4, 2019      </time>
      </div>

  </div>
          <div class="single-video-wrapper">
            <iframe width="560" height="315" src="https://www.youtube.com/embed/pxNrUg7t0Mg" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>        </div>

            <div class="tags">
      <a href="tag/babel/" rel="tag">Photoshop</a> <a href="tag/css-modules/" rel="tag">Drawings</a> <a href="tag/css-in-js/" rel="tag">Colors</a> <a href="tag/react/" rel="tag">Presentations</a> <a href="tag/webpack/" rel="tag">Shortcuts</a>  </div>

        </div>

        <div class="hero-article-ad" id="hero-article-ad">
        </div>

      </div>

    </header>

    <div class="header-gradient-after">
    <div class="header-gradient-content">
      <div class="header-gradient-content-inside">

        <div class="sharedaddy sd-sharing-enabled"><div class="robots-nocontent sd-block sd-social sd-social-text sd-sharing"><h3 class="sd-title">Share this:</h3><div class="sd-content"><ul><li class="share-twitter"><a rel="nofollow noopener noreferrer" data-shared="sharing-twitter-283102" class="share-twitter sd-button no-icon" href="https://twitter.com/intent/tweet?button_hashtag=ccresources&ref_src=twsrc%5Etfw" target="_blank" title="Click to share on Twitter"><span>Twitter</span></a></li><li class="share-facebook"><a rel="nofollow noopener noreferrer" data-href="http://ccresources.herokuapp.com/" class="share-facebook sd-button no-icon" href="https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Fccresources.herokuapp.com%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore" target="_blank" title="Click to share on Facebook"><span>Facebook</span></a></li><li class="share-end"></li></ul></div></div></div>
                <div class="bold-underline-links header-gradient-sponsor">
            <p>Help us out by sharing this with others <a href="http://ccresources.herokuapp.com/">CC Resources</a>
  </p>        </div>

      </div>
    </div>
  </div>
  </main>

  <div class="related-ads-comments-wrap">
    <div class="related-ads-comments">
            <div class="related-posts">


  <!-- Jetpack Related Posts is not supported in this context. -->

  </div>      <div class="end-of-article-ads">

        <div class="bsap-doubles side-by-side">

        <div id="bsap_1250418" class="bsarocks bsap_3469a2a501a9e18091036aa0c89f9dcb"></div>

      </div>

  </div>

  <section class="respond-area">



    <div class="comments-closed bold-underline-links">
      This video has been posted to aid designer and architects to learn. For any questions <a href="https://ymcmbennie.github.io/portfolio/">contact us</a>.
    </div>


  </section>      </div>
  </div>

    </div>
{% endblock content %}

flaskblog/templates/ardhi.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>Flask Blog - {{ title }}</title>
    {% else %}
        <title>Flask Blog</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">Flask Blog</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="/">Home</a>
              <a class="nav-item nav-link" href="/about">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              <a class="nav-item nav-link" href="/login">Login</a>
              <a class="nav-item nav-link" href="/register">Register</a>
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3>Our Sidebar</h3>
            <p class='text-muted'>You can put any information here you'd like.
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">Latest Posts</li>
                <li class="list-group-item list-group-item-light">Announcements</li>
                <li class="list-group-item list-group-item-light">Calendars</li>
                <li class="list-group-item list-group-item-light">etc</li>
              </ul>
            </p>
          </div>
        </div>
      </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

flaskblog/templates/create_post.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            <div class="form-group">
                {{ form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.title(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.content.label(class="form-control-label") }}
                {% if form.content.errors %}
                    {{ form.content(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.content.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.content(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock content %}

flaskblog/templates/new_article.html
 {% extends "layout.html" %}
{% block content %}
    <h1>New Article</h1>
    <form name="new_article_form" id="article" data-netlify="true" method="POST" class="forums-login-form">
      <h4>Fill the fields accordingly</h4>

      <div style="padding: 5px;" class="login-username login-field">
        <label for="user_login" class="screen-reader">Heading</label>
        <input type="text" name="log" id="Heading" class="input" value="" size="20" placeholder="Heading"><br>
      </div>
      <div style="padding: 5px;" class="login-password login-field">
        <label for="user_pass" class="screen-reader">Password</label>
        <textarea class="input" rows = "5" cols = "60" name = "description" placeholder="Article Content"></textarea><br>
      </div>
      <div style="padding: 5px;" class="login-password login-field">
        <label for="user_pass" class="screen-reader">Password</label>
        <textarea class="input" name="Tags" cols="20" rows="2" placeholder="Tags eg Grasshopper, Rhino, computation..."></textarea><br>
      </div>

      <div class="login-submit">
        <input type="hidden" name="redirect_to" value="/forums/">
        <input type="submit" name="wp-submit" id="wp-submit" class="button" value="Submit Article">
      </div>

    </form>
{% endblock content %}

flaskblog/templates/piotkowska.html
<head>
  <link href="https://cdn.osmbuildings.org/4.0.0/OSMBuildings.css" rel="stylesheet">
  <script src="https://cdn.osmbuildings.org/4.0.0/OSMBuildings.js"></script>
</head>

<body>
  <div id="map"></div>
  <script type="text/javascript">
      var osmb = new OSMBuildings({
    container: 'map',
    position: { latitude: 51.765029, longitude: 19.452172 },
    zoom: 18,
    minZoom: 15,
    maxZoom: 22
  });

  osmb.addMapTiles(
    'https://{s}.tiles.mapbox.com/v3/osmbuildings.kbpalbpk/{z}/{x}/{y}.png',
    {
      attribution: '© Data <a href="http://openstreetmap.org/copyright/">OpenStreetMap</a> · © Map <a href="http://mapbox.com">Mapbox</a>'
    }
  );

  osmb.addGeoJSONTiles('http://{s}.data.osmbuildings.org/0.2/anonymous/tile/{z}/{x}/{y}.json');
  </script>

flaskblog/templates/searchtmeplate.html
{% extends "layout.html" %}
{% block content %}
    <div class="all-site-wrap" id="all-site-wrap">
        <circle-text r="70" class="circle-text-videos">
          Search What you seek
        </circle-text>

        <svg width="624" height="443" viewBox="0 0 624 443" xmlns="http://www.w3.org/2000/svg" class="blob-top-right">
        <path d="M260 -0.99952C160.589 -0.999515 80 79.5892 80 179.001C80 278.412 160.589 359.001 260 359.001L624 359L624 -0.999535L260 -0.99952Z" fill="url(#orange-to-pink)" />
        </svg>
        <svg width="500" height="500" viewBox="0 0 500 500" xmlns="http://www.w3.org/2000/svg" class="blob-circle">
          <circle cx="250" cy="250" r="250" fill="url(#orange-to-pink)" />
        </svg>
        <svg width="250" height="250" viewBox="0 0 500 500" xmlns="http://www.w3.org/2000/svg" class="blob-circle-small">
          <circle cx="250" cy="250" r="250" />
        </svg>

        <header class="page-header" id="maincontent">

          <h1>Searching Portals</h1>

          <blockquote class="page-intro-p"><span>Pick one of the categories and search for what you want for your project or just take a look at the quality materials available</span><cite>&mdash; <a href="https://ymcmbennie.github.io/portfolio/">Benson Sanga</a></cite></blockquote>

          <svg viewBox="0 0 100 20" class="header-line-only">
          <path d="M 0 20 L 90 20 Q 100 20 100 10 L 100 0">
        </svg>

        </header>

        <div class="page-wrap page-wrap-max-width">

          <div class="video-grid">


          <article class="video-module">

          <div class="video-info">
            <h2>


              <a href="{{ url_for('main.tutorial001') }}">
                <span>
                  <span class="video-number">
                    001          </span>
                   People cutouts</span>
                <span class="watch-video-button">

                  <div>
                    <strong>Start Your search</strong>
                    <time>Last Updated<span>Mar 2019</span></time>
                  </div>
                </span>
                <div class="video-thumb">
                  <img class="video-thumbnail" src="https://i.ytimg.com/vi/pxNrUg7t0Mg/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBSKMkNKAnPCjbNKxeIYIiq0tunIQ" alt="Cganging back grounds">
                </div>
              </a>
            </h2>

            <div class="video-description">
              <p>A collection of 2D cutouts of people in high quality</p>
        <blockquote><p>Quoted to be the best collection ever. Idk im just filling in the text</p></blockquote>&hellip; <a href="{{ url_for('main.tutorial001') }}" class="read-more">Learn More</a>    </div>
          </div>
        </article>

        </div>

        <div class="post-a-job">
          <a href="{{ url_for('main.tutorial001') }}" class="button">See All</a>
          <br><br>
          ... over on the <a href="https://codepen.io/Projects/">CC-Resources tutorial Catalogue</a>, You can see all the objects by name <a href="{{ url_for('main.dwg') }}">Catalogue</a>.
        </div>
{% endblock content %}

flaskblog/templates/tutorials.html
{% extends "layout.html" %}
{% block content %}
    <div class="all-site-wrap" id="all-site-wrap">
        <circle-text r="70" class="circle-text-videos">
          Watch & Learn & Watch & Learn & Watch
        </circle-text>

        <svg width="624" height="443" viewBox="0 0 624 443" xmlns="http://www.w3.org/2000/svg" class="blob-top-right">
        <path d="M260 -0.99952C160.589 -0.999515 80 79.5892 80 179.001C80 278.412 160.589 359.001 260 359.001L624 359L624 -0.999535L260 -0.99952Z" fill="url(#orange-to-pink)" />
        </svg>
        <svg width="500" height="500" viewBox="0 0 500 500" xmlns="http://www.w3.org/2000/svg" class="blob-circle">
          <circle cx="250" cy="250" r="250" fill="url(#orange-to-pink)" />
        </svg>
        <svg width="250" height="250" viewBox="0 0 500 500" xmlns="http://www.w3.org/2000/svg" class="blob-circle-small">
          <circle cx="250" cy="250" r="250" />
        </svg>

        <header class="page-header" id="maincontent">

          <h1>Video Tutorials</h1>

          <blockquote class="page-intro-p"><span>I found I could say things with color and shapes that I couldn’t say any other way – things I had no words for.</span><cite>&mdash; <a href="https://quotesondesign.com/georgia-okeeffe/">Georgia O'Keeffe</a></cite></blockquote>

          <svg viewBox="0 0 100 20" class="header-line-only">
          <path d="M 0 20 L 90 20 Q 100 20 100 10 L 100 0">
        </svg>

        </header>

        <div class="page-wrap page-wrap-max-width">

          <div class="video-grid">

          {% for video in videos %}
          <article class="video-module">

          <div class="video-info">
            <h2>


              <a href="{{ url_for('main.tutorial001') }}">
                <span>
                  <span class="video-number">
                    {{ video.number }}          </span>
                   {{ video.title }}p</span>
                <span class="watch-video-button">
                  <svg class="icon-play" width="35px" height="35px">
                    <use xlink:href="#icon-play"></use>
                  </svg>
                  <div>
                    <strong>Watch the video</strong>
                    <time>Running Time: <span>{{ video.time }}</span></time>
                  </div>
                </span>
                <div class="video-thumb">
                  <img class="video-thumbnail" src="https://i.ytimg.com/vi/pxNrUg7t0Mg/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBSKMkNKAnPCjbNKxeIYIiq0tunIQ" alt="Cganging back grounds">
                </div>
              </a>
            </h2>

            <div class="video-description">
              <p>{{ video.shortDescription }}</p>
        <blockquote><p>{{ video.summary }}</p></blockquote>&hellip; <a href="{{ url_for('main.tutorial001') }}" class="read-more">Learn More</a>    </div>
          </div>
        </article>
        {% endfor %}
        </div>

        <div class="post-a-job">
          <a href="{{ url_for('main.tutorial001') }}" class="button">New Tutorial</a>
          <br><br>
          ... over on the <a href="https://codepen.io/Projects/">CC-Resources tutorial Board</a>, which places the tutorial here and on <a href="https://shoptalkshow.com/jobs">CC-Resources</a>.
        </div>
{% endblock content %}